version: '3'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: confia
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
    ports:
      - "15432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - postgres-network
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file: 
      - docker.env
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge
